In [3]:
import pandas as pd
import numpy as np
import matplotlib
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import collections
import plotly.figure_factory as ff

from sklearn.preprocessing import MinMaxScaler
df= pd.read_csv("Stats_summary_core.csv")

In [4]:
df.head()

,client_id,stats_timestamp,total_attached_user,total_rejected_user,peak_upload_speed,peak_download_speed,enodeb_shutdown_count,handover_failure_count,bearer_active_user_count,bearer_rejected_user_count,...,label_outlier_total_users,Z-score_total_dropped_packets,label_Z-score_total_dropped_packets,label_outlier_total_dropped_packets,Z-score_enodeb_connected_count,label_Z-score_enodeb_connected_count,label_outlier_enodeb_connected_count,Z-score_enodeb_connection_status,label_Z-score_enodeb_connection_status,label_outlier_enodeb_connection_status
0,BETAZRPDCOR001,2022-03-01 14:55:27,2,0,45751,0,0,0,0,0,...,0,1.17,0,0,-1.17,0,0,1.17,0,0
1,BETAZRPDCOR001,2022-03-01 15:16:59,2,0,45901,0,0,0,0,0,...,0,1.17,0,0,-1.17,0,0,1.17,0,0
2,BETAZRPDCOR001,2022-03-01 15:18:01,2,0,45901,0,0,0,0,0,...,0,1.17,0,0,-1.17,0,0,1.17,0,0
3,BETAZRPDCOR001,2022-03-01 15:24:02,2,0,45921,0,0,0,0,0,...,0,1.17,0,0,-1.17,0,0,1.17,0,0
4,BETAZRPDCOR001,2022-03-01 15:30:02,2,0,45940,0,0,0,0,0,...,0,1.17,0,0,-1.17,0,0,1.17,0,0

In [87]:
df.columns

Index(['client_id', 'stats_timestamp', 'total_attached_user',
       'total_rejected_user', 'peak_upload_speed', 'peak_download_speed',
       'enodeb_shutdown_count', 'handover_failure_count',
       'bearer_active_user_count', 'bearer_rejected_user_count', 'total_users',
       'total_dropped_packets', 'enodeb_connected_count',
       'enodeb_connection_status', 'Z-score_peak_upload_speed',
       'label_Z-score_peak_upload_speed', 'label_outlier_peak_upload_speed',
       'Z-score_total_attached_user', 'label_Z-score_total_attached_user',
       'label_outlier_total_attached_user', 'Z-score_handover_failure_count',
       'label_Z-score_handover_failure_count',
       'label_outlier_handover_failure_count',
       'Z-score_bearer_active_user_count',
       'label_Z-score_bearer_active_user_count',
       'label_outlier_bearer_active_user_count', 'Z-score_total_users',
       'label_Z-score_total_users', 'label_outlier_total_users',
       'Z-score_total_dropped_packets', 'label_Z-score_total_dropped_packets',
       'label_outlier_total_dropped_packets', 'Z-score_enodeb_connected_count',
       'label_Z-score_enodeb_connected_count',
       'label_outlier_enodeb_connected_count',
       'Z-score_enodeb_connection_status',
       'label_Z-score_enodeb_connection_status',
       'label_outlier_enodeb_connection_status'],
      dtype='object')

## Anomaly_Data Class object

In [89]:
class Anomaly_Data:
    def __init__(self, df,time_col):
        self.df=df
        self.time_col = time_col 
    
    def get_client_and_timestamp(self):
        self.client = self.df.client_id
        self.time_col= self.df.stats_timestamp
    
        
    def find_label_df(self):
        filter_col = [col for col in self.df if col.startswith('label')]
        
        self.label_df=self.df[filter_col]
        self.nrow, self.ncol= label_df.shape
        
    def sparse_to_dense(self):
        self.anomaly_dic={}
        for i in range(self.nrow):
            for j in range(self.ncol):

                if(self.label_df.iloc[i,j] == 0):
                    pass
                else:

                    self.anomaly_dic[str(i)+"_"+str(j)] = self.time_col[i][:16]
                     
                    # Map i to Device, map j to Anomaly_Feature
                    # Store timestamp

In [91]:
anomaly_obj = Anomaly_Data(df,df.stats_timestamp)
anomaly_obj.get_client_and_timestamp()
anomaly_obj.find_label_df()

anomaly_obj.sparse_to_dense()

## Playground

In [59]:
anomaly_df.label_df.head()

,label_Z-score_peak_upload_speed,label_outlier_peak_upload_speed,label_Z-score_total_attached_user,label_outlier_total_attached_user,label_Z-score_handover_failure_count,label_outlier_handover_failure_count,label_Z-score_bearer_active_user_count,label_outlier_bearer_active_user_count,label_Z-score_total_users,label_outlier_total_users,label_Z-score_total_dropped_packets,label_outlier_total_dropped_packets,label_Z-score_enodeb_connected_count,label_outlier_enodeb_connected_count,label_Z-score_enodeb_connection_status,label_outlier_enodeb_connection_status
0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [30]:
label_df = df[filter_col]

In [51]:
nrow, ncol= label_df.shape

In [84]:
anomaly_dic= {}

In [85]:
for i in range(nrow):
    for j in range(ncol):
        
        if(label_df.iloc[i,j] == 0):
            pass
        else:
            
            anomaly_dic[str(i)+"_"+str(j)] = df.stats_timestamp[i][:16]
            # Map i to Device, map j to Anomaly_Feature
            # Store timestamp

In [86]:
anomaly_dic.to

{'0_3': '2022-03-01 14:55',
 '1_3': '2022-03-01 15:16',
 '2_3': '2022-03-01 15:18',
 '3_3': '2022-03-01 15:24',
 '4_3': '2022-03-01 15:30',
 '5_3': '2022-03-01 15:36',
 '6_3': '2022-03-01 15:42',
 '7_3': '2022-03-01 15:48',
 '8_3': '2022-03-01 15:54',
 '9_3': '2022-03-01 16:00',
 '10_3': '2022-03-01 16:05',
 '11_3': '2022-03-01 16:10',
 '12_3': '2022-03-01 16:15',
 '13_3': '2022-03-01 16:20',
 '14_3': '2022-03-01 16:25',
 '15_3': '2022-03-01 16:30',
 '16_3': '2022-03-01 16:35',
 '17_3': '2022-03-01 16:40',
 '18_3': '2022-03-01 16:45',
 '19_3': '2022-03-01 16:50',
 '20_3': '2022-03-01 16:55',
 '20_4': '2022-03-01 16:55',
 '20_5': '2022-03-01 16:55',
 '20_6': '2022-03-01 16:55',
 '20_7': '2022-03-01 16:55',
 '20_8': '2022-03-01 16:55',
 '20_9': '2022-03-01 16:55',
 '21_3': '2022-03-01 17:00',
 '21_4': '2022-03-01 17:00',
 '21_5': '2022-03-01 17:00',
 '21_6': '2022-03-01 17:00',
 '21_7': '2022-03-01 17:00',
 '21_8': '2022-03-01 17:00',
 '21_9': '2022-03-01 17:00',
 '22_3': '2022-03-01 17:05',
 '22_4': '2022-03-01 17:05',
 '22_5': '2022-03-01 17:05',
 '22_6': '2022-03-01 17:05',
 '22_7': '2022-03-01 17:05',
 '22_8': '2022-03-01 17:05',
 '22_9': '2022-03-01 17:05',
 '23_3': '2022-03-01 17:10',
 '23_4': '2022-03-01 17:10',
 '23_5': '2022-03-01 17:10',
 '23_6': '2022-03-01 17:10',
 '23_7': '2022-03-01 17:10',
 '23_8': '2022-03-01 17:10',
 '23_9': '2022-03-01 17:10',
 '24_3': '2022-03-01 17:15',
 '24_4': '2022-03-01 17:15',
 '24_5': '2022-03-01 17:15',
 '24_6': '2022-03-01 17:15',
 '24_7': '2022-03-01 17:15',
 '24_8': '2022-03-01 17:15',
 '24_9': '2022-03-01 17:15',
 '25_3': '2022-03-01 17:20',
 '25_4': '2022-03-01 17:20',
 '25_5': '2022-03-01 17:20',
 '25_6': '2022-03-01 17:20',
 '25_7': '2022-03-01 17:20',
 '25_8': '2022-03-01 17:20',
 '25_9': '2022-03-01 17:20',
 '26_3': '2022-03-01 17:25',
 '26_4': '2022-03-01 17:25',
 '26_5': '2022-03-01 17:25',
 '26_6': '2022-03-01 17:25',
 '26_7': '2022-03-01 17:25',
 '26_8': '2022-03-01 17:25',
 '26_9': '2022-03-01 17:25',
 '27_3': '2022-03-01 17:30',
 '27_4': '2022-03-01 17:30',
 '27_5': '2022-03-01 17:30',
 '27_6': '2022-03-01 17:30',
 '27_7': '2022-03-01 17:30',
 '27_8': '2022-03-01 17:30',
 '27_9': '2022-03-01 17:30',
 '28_3': '2022-03-01 17:35',
 '28_4': '2022-03-01 17:35',
 '28_5': '2022-03-01 17:35',
 '28_6': '2022-03-01 17:35',
 '28_7': '2022-03-01 17:35',
 '28_8': '2022-03-01 17:35',
 '28_9': '2022-03-01 17:35',
 '29_3': '2022-03-01 17:40',
 '29_4': '2022-03-01 17:40',
 '29_5': '2022-03-01 17:40',
 '29_6': '2022-03-01 17:40',
 '29_7': '2022-03-01 17:40',
 '29_8': '2022-03-01 17:40',
 '29_9': '2022-03-01 17:40',
 '30_3': '2022-03-01 17:41',
 '30_4': '2022-03-01 17:41',
 '30_5': '2022-03-01 17:41',
 '30_6': '2022-03-01 17:41',
 '30_7': '2022-03-01 17:41',
 '30_8': '2022-03-01 17:41',
 '30_9': '2022-03-01 17:41',
 '31_3': '2022-03-01 17:50',
 '31_4': '2022-03-01 17:50',
 '31_5': '2022-03-01 17:50',
 '31_6': '2022-03-01 17:50',
 '31_7': '2022-03-01 17:50',
 '31_8': '2022-03-01 17:50',
 '31_9': '2022-03-01 17:50',
 '32_0': '2022-03-01 17:55',
 '32_1': '2022-03-01 17:55',
 '32_3': '2022-03-01 17:55',
 '32_4': '2022-03-01 17:55',
 '32_5': '2022-03-01 17:55',
 '32_6': '2022-03-01 17:55',
 '32_7': '2022-03-01 17:55',
 '32_8': '2022-03-01 17:55',
 '32_9': '2022-03-01 17:55',
 '33_3': '2022-03-01 18:00',
 '33_4': '2022-03-01 18:00',
 '33_5': '2022-03-01 18:00',
 '33_6': '2022-03-01 18:00',
 '33_7': '2022-03-01 18:00',
 '33_8': '2022-03-01 18:00',
 '33_9': '2022-03-01 18:00',
 '34_3': '2022-03-01 18:05',
 '34_4': '2022-03-01 18:05',
 '34_5': '2022-03-01 18:05',
 '34_6': '2022-03-01 18:05',
 '34_7': '2022-03-01 18:05',
 '34_8': '2022-03-01 18:05',
 '34_9': '2022-03-01 18:05',
 '35_3': '2022-03-01 18:10',
 '35_4': '2022-03-01 18:10',
 '35_5': '2022-03-01 18:10',
 '35_6': '2022-03-01 18:10',
 '35_7': '2022-03-01 18:10',
 '35_8': '2022-03-01 18:10',
 '35_9': '2022-03-01 18:10',
 '36_3': '2022-03-01 18:15',
 '36_4': '2022-03-01 18:15',
 '36_5': '2022-03-01 18:15',
 '36_6': '2022-03-01 18:15',
 '36_7': '2022-03-01 18:15',
 '36_8': '2022-03-01 18:15',
 '36_9': '2022-03-01 18:15',
 '37_3': '2022-03-01 18:20',
 '37_4': '2022-03-01 18:20',
 '37_5': '2022-03-01 18:20',
 '37_6': '2022-03-01 18:20',
 '37_7': '2022-03-01 18:20',
 '37_8': '2022-03-01 18:20',
 '37_9': '2022-03-01 18:20',
 '38_3': '2022-03-01 18:25',
 '39_3': '2022-03-01 18:30',
 '40_3': '2022-03-01 18:35',
 '41_3': '2022-03-01 18:40',
 '42_3': '2022-03-01 18:45',
 '43_3': '2022-03-01 18:50',
 '44_3': '2022-03-01 18:55',
 '45_3': '2022-03-01 19:00',
 '46_3': '2022-03-01 19:05',
 '47_3': '2022-03-01 19:10',
 '48_3': '2022-03-01 19:15',
 '49_0': '2022-03-01 19:20',
 '49_1': '2022-03-01 19:20',
 '49_3': '2022-03-01 19:20',
 '50_3': '2022-03-01 19:25',
 '50_8': '2022-03-01 19:25',
 '50_9': '2022-03-01 19:25',
 '51_3': '2022-03-01 19:30',
 '51_8': '2022-03-01 19:30',
 '51_9': '2022-03-01 19:30',
 '52_3': '2022-03-01 19:35',
 '52_8': '2022-03-01 19:35',
 '52_9': '2022-03-01 19:35',
 '53_3': '2022-03-01 19:40',
 '53_8': '2022-03-01 19:40',
 '53_9': '2022-03-01 19:40',
 '54_3': '2022-03-01 19:45',
 '54_8': '2022-03-01 19:45',
 '54_9': '2022-03-01 19:45',
 '55_3': '2022-03-01 19:50',
 '55_8': '2022-03-01 19:50',
 '55_9': '2022-03-01 19:50',
 '56_3': '2022-03-01 19:55',
 '56_8': '2022-03-01 19:55',
 '56_9': '2022-03-01 19:55',
 '57_3': '2022-03-01 20:00',
 '57_8': '2022-03-01 20:00',
 '57_9': '2022-03-01 20:00',
 '58_3': '2022-03-01 20:05',
 '58_8': '2022-03-01 20:05',
 '58_9': '2022-03-01 20:05',
 '59_3': '2022-03-01 20:10',
 '59_8': '2022-03-01 20:10',
 '59_9': '2022-03-01 20:10',
 '60_3': '2022-03-01 20:15',
 '60_8': '2022-03-01 20:15',
 '60_9': '2022-03-01 20:15',
 '61_3': '2022-03-01 20:20',
 '61_8': '2022-03-01 20:20',
 '61_9': '2022-03-01 20:20',
 '62_3': '2022-03-01 20:25',
 '63_3': '2022-03-01 20:30',
 '64_3': '2022-03-01 20:35',
 '65_3': '2022-03-01 20:40',
 '66_3': '2022-03-01 20:45',
 '66_8': '2022-03-01 20:45',
 '66_9': '2022-03-01 20:45',
 '67_3': '2022-03-01 20:50',
 '67_8': '2022-03-01 20:50',
 '67_9': '2022-03-01 20:50',
 '68_3': '2022-03-01 20:55',
 '68_8': '2022-03-01 20:55',
 '68_9': '2022-03-01 20:55',
 '69_3': '2022-03-01 21:00',
 '69_8': '2022-03-01 21:00',
 '69_9': '2022-03-01 21:00',
 '70_3': '2022-03-01 21:05',
 '70_8': '2022-03-01 21:05',
 '70_9': '2022-03-01 21:05',
 '71_3': '2022-03-01 21:10',
 '71_8': '2022-03-01 21:10',
 '71_9': '2022-03-01 21:10',
 '72_3': '2022-03-01 21:15',
 '72_8': '2022-03-01 21:15',
 '72_9': '2022-03-01 21:15',
 '73_3': '2022-03-01 21:20',
 '73_8': '2022-03-01 21:20',
 '73_9': '2022-03-01 21:20',
 '74_3': '2022-03-01 21:25',
 '74_8': '2022-03-01 21:25',
 '74_9': '2022-03-01 21:25',
 '75_3': '2022-03-01 21:30',
 '75_8': '2022-03-01 21:30',
 '75_9': '2022-03-01 21:30',
 '76_3': '2022-03-01 21:35',
 '76_8': '2022-03-01 21:35',
 '76_9': '2022-03-01 21:35',
 '77_3': '2022-03-01 21:40',
 '77_8': '2022-03-01 21:40',
 '77_9': '2022-03-01 21:40',
 '78_3': '2022-03-01 21:45',
 '78_8': '2022-03-01 21:45',
 '78_9': '2022-03-01 21:45',
 '79_3': '2022-03-01 21:50',
 '79_8': '2022-03-01 21:50',
 '79_9': '2022-03-01 21:50',
 '80_3': '2022-03-01 21:55',
 '81_3': '2022-03-01 22:00',
 '82_3': '2022-03-01 22:05',
 '83_3': '2022-03-01 22:10',
 '84_3': '2022-03-01 22:15',
 '85_3': '2022-03-01 22:20',
 '86_0': '2022-03-01 22:25',
 '86_1': '2022-03-01 22:25',
 '86_3': '2022-03-01 22:25',
 '87_3': '2022-03-01 22:30',
 '88_3': '2022-03-01 22:35',
 '89_3': '2022-03-01 22:40',
 '90_3': '2022-03-01 22:45',
 '91_3': '2022-03-01 22:50',
 '92_3': '2022-03-01 22:55',
 '93_3': '2022-03-01 23:00',
 '94_3': '2022-03-01 23:05',
 '94_8': '2022-03-01 23:05',
 '94_9': '2022-03-01 23:05',
 '95_3': '2022-03-01 23:10',
 '95_8': '2022-03-01 23:10',
 '95_9': '2022-03-01 23:10',
 '96_3': '2022-03-01 23:15',
 '96_8': '2022-03-01 23:15',
 '96_9': '2022-03-01 23:15',
 '97_3': '2022-03-01 23:20',
 '97_8': '2022-03-01 23:20',
 '97_9': '2022-03-01 23:20',
 '98_3': '2022-03-01 23:25',
 '98_8': '2022-03-01 23:25',
 '98_9': '2022-03-01 23:25',
 '99_3': '2022-03-01 23:30',
 '99_8': '2022-03-01 23:30',
 '99_9': '2022-03-01 23:30',
 '100_3': '2022-03-01 23:35',
 '100_8': '2022-03-01 23:35',
 '100_9': '2022-03-01 23:35',
 '101_3': '2022-03-01 23:40',
 '101_8': '2022-03-01 23:40',
 '101_9': '2022-03-01 23:40',
 '102_3': '2022-03-01 23:45',
 '102_8': '2022-03-01 23:45',
 '102_9': '2022-03-01 23:45',
 '103_3': '2022-03-01 23:50',
 '103_8': '2022-03-01 23:50',
 '103_9': '2022-03-01 23:50',
 '104_3': '2022-03-01 23:55',
 '104_8': '2022-03-01 23:55',
 '104_9': '2022-03-01 23:55',
 '105_3': '2022-03-02 00:00',
 '105_8': '2022-03-02 00:00',
 '105_9': '2022-03-02 00:00',
 '106_3': '2022-03-02 00:05',
 '106_8': '2022-03-02 00:05',
 '106_9': '2022-03-02 00:05',
 '107_3': '2022-03-02 00:10',
 '107_8': '2022-03-02 00:10',
 '107_9': '2022-03-02 00:10',
 '108_3': '2022-03-02 00:15',
 '108_8': '2022-03-02 00:15',
 '108_9': '2022-03-02 00:15',
 '109_3': '2022-03-02 00:20',
 '109_8': '2022-03-02 00:20',
 '109_9': '2022-03-02 00:20',
 '110_3': '2022-03-02 00:25',
 '110_8': '2022-03-02 00:25',
 '110_9': '2022-03-02 00:25',
 '111_3': '2022-03-02 00:30',
 '111_8': '2022-03-02 00:30',
 '111_9': '2022-03-02 00:30',
 '112_3': '2022-03-02 00:35',
 '112_8': '2022-03-02 00:35',
 '112_9': '2022-03-02 00:35',
 '113_3': '2022-03-02 00:40',
 '114_3': '2022-03-02 00:45',
 '115_3': '2022-03-02 00:50',
 '116_3': '2022-03-02 00:55',
 '117_3': '2022-03-02 01:00',
 '118_3': '2022-03-02 01:05',
 '119_3': '2022-03-02 01:10',
 '120_3': '2022-03-02 01:15',
 '121_3': '2022-03-02 01:20',
 '122_3': '2022-03-02 01:25',
 '123_3': '2022-03-02 01:30',
 '124_3': '2022-03-02 01:35',
 '125_3': '2022-03-02 01:40',
 '126_3': '2022-03-02 01:45',
 '127_3': '2022-03-02 01:50',
 '128_3': '2022-03-02 01:55',
 '129_3': '2022-03-02 02:00',
 '130_0': '2022-03-02 02:05',
 '130_1': '2022-03-02 02:05',
 '130_3': '2022-03-02 02:05',
 '131_3': '2022-03-02 02:10',
 '132_3': '2022-03-02 02:15',
 '133_3': '2022-03-02 02:20',
 '134_3': '2022-03-02 02:25',
 '135_3': '2022-03-02 02:30',
 '136_3': '2022-03-02 02:35',
 '137_3': '2022-03-02 02:40',
 '138_3': '2022-03-02 02:45',
 '139_3': '2022-03-02 02:50',
 '140_3': '2022-03-02 02:55',
 '141_3': '2022-03-02 03:00',
 '142_3': '2022-03-02 03:05',
 '143_3': '2022-03-02 03:10',
 '144_3': '2022-03-02 03:15',
 '145_3': '2022-03-02 03:20',
 '146_3': '2022-03-02 03:25',
 '147_3': '2022-03-02 03:30',
 '148_3': '2022-03-02 03:35',
 '149_0': '2022-03-02 03:40',
 '149_1': '2022-03-02 03:40',
 '149_3': '2022-03-02 03:40',
 '150_3': '2022-03-02 03:45',
 '151_3': '2022-03-02 03:50',
 '152_3': '2022-03-02 03:55',
 '153_3': '2022-03-02 04:00',
 '154_3': '2022-03-02 04:05',
 '155_3': '2022-03-02 04:10',
 '156_3': '2022-03-02 04:15',
 '157_3': '2022-03-02 04:20',
 '158_3': '2022-03-02 04:25',
 '159_3': '2022-03-02 04:30',
 '160_3': '2022-03-02 04:35',
 '161_3': '2022-03-02 04:40',
 '162_3': '2022-03-02 04:45',
 '163_3': '2022-03-02 04:50',
 '164_3': '2022-03-02 04:55',
 '165_3': '2022-03-02 05:00',
 '166_3': '2022-03-02 05:05',
 '167_3': '2022-03-02 05:10',
 '168_3': '2022-03-02 05:15',
 '169_3': '2022-03-02 05:20',
 '170_3': '2022-03-02 05:25',
 '171_3': '2022-03-02 05:30',
 '172_3': '2022-03-02 05:35',
 '173_3': '2022-03-02 05:40',
 '174_3': '2022-03-02 05:45',
 '175_3': '2022-03-02 05:50',
 '176_3': '2022-03-02 05:55',
 '177_3': '2022-03-02 06:00',
 '178_3': '2022-03-02 06:05',
 '179_3': '2022-03-02 06:10',
 '180_3': '2022-03-02 06:15',
 '181_3': '2022-03-02 06:20',
 '182_3': '2022-03-02 06:25',
 '183_0': '2022-03-02 06:30',
 '183_1': '2022-03-02 06:30',
 '183_3': '2022-03-02 06:30',
 '184_3': '2022-03-02 06:35',
 '185_3': '2022-03-02 06:40',
 '186_3': '2022-03-02 06:45',
 '187_3': '2022-03-02 06:50',
 '188_3': '2022-03-02 06:55',
 '189_3': '2022-03-02 07:00',
 '190_3': '2022-03-02 07:05',
 '191_3': '2022-03-02 07:10',
 '192_3': '2022-03-02 07:15',
 '193_3': '2022-03-02 07:20',
 '194_3': '2022-03-02 07:25',
 '195_3': '2022-03-02 07:30',
 '196_3': '2022-03-02 07:35',
 '197_3': '2022-03-02 07:40',
 '198_3': '2022-03-02 07:45',
 '199_3': '2022-03-02 07:50',
 '200_3': '2022-03-02 07:55',
 '201_3': '2022-03-02 08:00',
 '202_3': '2022-03-02 08:05',
 '203_0': '2022-03-02 08:10',
 '203_1': '2022-03-02 08:10',
 '203_3': '2022-03-02 08:10',
 '204_3': '2022-03-02 08:15',
 '205_0': '2022-03-02 08:20',
 '205_1': '2022-03-02 08:20',
 '205_3': '2022-03-02 08:20',
 '206_0': '2022-03-02 08:25',
 '206_1': '2022-03-02 08:25',
 '206_3': '2022-03-02 08:25',
 '207_0': '2022-03-02 08:30',
 '207_1': '2022-03-02 08:30',
 '207_3': '2022-03-02 08:30',
 '208_3': '2022-03-02 08:35',
 '209_3': '2022-03-02 08:40',
 '210_0': '2022-03-02 08:45',
 '210_3': '2022-03-02 08:45',
 '211_0': '2022-03-02 08:50',
 '211_1': '2022-03-02 08:50',
 '211_3': '2022-03-02 08:50',
 '212_3': '2022-03-02 08:55',
 '213_3': '2022-03-02 09:00',
 '214_3': '2022-03-02 09:05',
 '215_3': '2022-03-02 09:10',
 '216_3': '2022-03-02 09:15',
 '217_0': '2022-03-02 09:20',
 '217_1': '2022-03-02 09:20',
 '217_3': '2022-03-02 09:20',
 '218_3': '2022-03-02 09:25',
 '219_3': '2022-03-02 09:30',
 '220_3': '2022-03-02 09:35',
 '221_3': '2022-03-02 09:40',
 '222_3': '2022-03-02 09:45',
 '223_3': '2022-03-02 09:50',
 '224_3': '2022-03-02 09:55',
 '225_3': '2022-03-02 10:00',
 '226_3': '2022-03-02 10:05',
 '227_3': '2022-03-02 10:10',
 '228_0': '2022-03-02 10:15',
 '228_1': '2022-03-02 10:15',
 '228_3': '2022-03-02 10:15',
 '229_3': '2022-03-02 10:20',
 '230_3': '2022-03-02 10:25',
 '231_3': '2022-03-02 10:30',
 '232_3': '2022-03-02 10:35',
 '233_3': '2022-03-02 10:40',
 '234_3': '2022-03-02 10:45',
 '235_3': '2022-03-02 10:50',
 '236_3': '2022-03-02 10:55',
 '237_3': '2022-03-02 11:00',
 '238_3': '2022-03-02 11:05',
 '239_3': '2022-03-02 11:10',
 '240_0': '2022-03-02 11:15',
 '240_1': '2022-03-02 11:15',
 '240_3': '2022-03-02 11:15',
 '241_3': '2022-03-02 11:20',
 '242_3': '2022-03-02 11:25',
 '243_3': '2022-03-02 11:30',
 '244_3': '2022-03-02 11:35',
 '245_3': '2022-03-02 11:40',
 '246_3': '2022-03-02 11:45',
 '247_3': '2022-03-02 11:50',
 '248_3': '2022-03-02 11:55',
 '249_3': '2022-03-02 12:00',
 '250_3': '2022-03-02 12:05',
 '251_3': '2022-03-02 12:10',
 '252_3': '2022-03-02 12:15',
 '253_0': '2022-03-02 12:20',
 '253_1': '2022-03-02 12:20',
 '253_3': '2022-03-02 12:20',
 '254_3': '2022-03-02 12:25',
 '255_3': '2022-03-02 12:30',
 '256_3': '2022-03-02 12:35',
 '257_3': '2022-03-02 12:40',
 '258_3': '2022-03-02 12:45',
 '259_3': '2022-03-02 12:50',
 '260_3': '2022-03-02 12:55',
 '261_3': '2022-03-02 13:00',
 '262_3': '2022-03-02 13:05',
 '263_3': '2022-03-02 13:10',
 '264_3': '2022-03-02 13:15',
 '265_3': '2022-03-02 13:20',
 '266_3': '2022-03-02 13:25',
 '267_3': '2022-03-02 13:30',
 '268_3': '2022-03-02 13:35',
 '269_3': '2022-03-02 13:40',
 '270_3': '2022-03-02 13:45',
 '271_3': '2022-03-02 13:50',
 '272_3': '2022-03-02 13:55',
 '273_3': '2022-03-02 14:00',
 '274_3': '2022-03-02 14:05',
 '275_3': '2022-03-02 14:10',
 '276_3': '2022-03-02 14:15',
 '277_3': '2022-03-02 14:20',
 '278_3': '2022-03-02 14:25',
 '279_3': '2022-03-02 14:30',
 '280_3': '2022-03-02 14:35',
 '281_3': '2022-03-02 14:40',
 '282_3': '2022-03-02 14:45',
 '283_3': '2022-03-02 14:50',
 '284_3': '2022-03-02 14:55',
 '285_3': '2022-03-02 15:00',
 '286_3': '2022-03-02 15:05',
 '287_0': '2022-03-02 15:10',
 '287_1': '2022-03-02 15:10',
 '287_3': '2022-03-02 15:10',
 '288_3': '2022-03-02 15:15',
 '289_3': '2022-03-02 15:20',
 '290_3': '2022-03-02 15:25',
 '291_3': '2022-03-02 15:30',
 '292_3': '2022-03-02 15:35',
 '293_3': '2022-03-02 15:40',
 '294_3': '2022-03-02 15:45',
 '295_3': '2022-03-02 15:50',
 '296_0': '2022-03-02 15:55',
 '296_1': '2022-03-02 15:55',
 '296_3': '2022-03-02 15:55',
 '297_3': '2022-03-02 16:00',
 '298_3': '2022-03-02 16:05',
 '299_3': '2022-03-02 16:10',
 '300_0': '2022-03-02 16:15',
 '300_1': '2022-03-02 16:15',
 '300_3': '2022-03-02 16:15',
 '301_0': '2022-03-02 16:20',
 '301_1': '2022-03-02 16:20',
 '301_3': '2022-03-02 16:20',
 '302_3': '2022-03-02 16:25',
 '303_3': '2022-03-02 16:30',
 '304_3': '2022-03-02 16:35',
 '305_3': '2022-03-02 16:40',
 '306_3': '2022-03-02 16:45',
 '307_3': '2022-03-02 16:50',
 '308_3': '2022-03-02 16:55',
 '309_3': '2022-03-02 17:00',
 '310_3': '2022-03-02 17:05',
 '311_3': '2022-03-02 17:10',
 '312_3': '2022-03-02 17:15',
 '313_3': '2022-03-02 17:20',
 '314_3': '2022-03-02 17:25',
 '315_3': '2022-03-02 17:30',
 '316_3': '2022-03-02 17:35',
 '317_3': '2022-03-02 17:40',
 '318_3': '2022-03-02 17:45',
 '319_3': '2022-03-02 17:50',
 '320_3': '2022-03-02 17:55',
 '321_3': '2022-03-02 18:00',
 '322_0': '2022-03-02 18:05',
 '322_1': '2022-03-02 18:05',
 '322_3': '2022-03-02 18:05',
 '323_3': '2022-03-02 18:10',
 '324_3': '2022-03-02 18:15',
 '325_3': '2022-03-02 18:20',
 '326_3': '2022-03-02 18:25',
 '327_3': '2022-03-02 18:30',
 '328_3': '2022-03-02 18:35',
 '329_3': '2022-03-02 18:40',
 '330_3': '2022-03-02 18:45',
 '331_3': '2022-03-02 18:50',
 '332_3': '2022-03-02 18:55',
 '333_3': '2022-03-02 19:00',
 '334_0': '2022-03-02 19:05',
 '334_1': '2022-03-02 19:05',
 '334_3': '2022-03-02 19:05',
 '335_3': '2022-03-02 19:10',
 '336_3': '2022-03-02 19:15',
 '337_3': '2022-03-02 19:20',
 '338_3': '2022-03-02 19:25',
 '339_3': '2022-03-02 19:30',
 '340_3': '2022-03-02 19:35',
 '341_3': '2022-03-02 19:40',
 '342_3': '2022-03-02 19:45',
 '343_3': '2022-03-02 19:50',
 '344_3': '2022-03-02 19:55',
 '345_3': '2022-03-02 20:00',
 '346_3': '2022-03-02 20:05',
 '347_3': '2022-03-02 20:10',
 '348_3': '2022-03-02 20:15',
 '349_3': '2022-03-02 20:20',
 '350_3': '2022-03-02 20:25',
 '351_3': '2022-03-02 20:30',
 '352_3': '2022-03-02 20:35',
 '353_3': '2022-03-02 20:40',
 '354_3': '2022-03-02 20:45',
 '355_3': '2022-03-02 20:50',
 '356_3': '2022-03-02 20:55',
 '357_3': '2022-03-02 21:00',
 '358_3': '2022-03-02 21:05',
 '359_3': '2022-03-02 21:10',
 '360_3': '2022-03-02 21:15',
 '361_3': '2022-03-02 21:20',
 '362_3': '2022-03-02 21:25',
 '363_3': '2022-03-02 21:30',
 '364_3': '2022-03-02 21:35',
 '365_3': '2022-03-02 21:40',
 '366_3': '2022-03-02 21:45',
 '367_3': '2022-03-02 21:50',
 '368_0': '2022-03-02 21:55',
 '368_1': '2022-03-02 21:55',
 '368_3': '2022-03-02 21:55',
 '369_3': '2022-03-02 22:00',
 '370_3': '2022-03-02 22:05',
 '371_3': '2022-03-02 22:10',
 '372_3': '2022-03-02 22:15',
 '373_3': '2022-03-02 22:20',
 '374_3': '2022-03-02 22:25',
 '375_3': '2022-03-02 22:30',
 '376_3': '2022-03-02 22:35',
 '377_3': '2022-03-02 22:40',
 '378_3': '2022-03-02 22:45',
 '379_3': '2022-03-02 22:50',
 '380_3': '2022-03-02 22:55',
 '381_3': '2022-03-02 23:00',
 '382_3': '2022-03-02 23:05',
 '383_3': '2022-03-02 23:10',
 '384_3': '2022-03-02 23:15',
 '385_3': '2022-03-02 23:20',
 '386_3': '2022-03-02 23:25',
 '387_3': '2022-03-02 23:30',
 '388_3': '2022-03-02 23:35',
 '389_3': '2022-03-02 23:40',
 '389_7': '2022-03-02 23:40',
 '389_8': '2022-03-02 23:40',
 '389_9': '2022-03-02 23:40',
 '390_3': '2022-03-02 23:45',
 '390_7': '2022-03-02 23:45',
 '390_8': '2022-03-02 23:45',
 '390_9': '2022-03-02 23:45',
 '391_3': '2022-03-02 23:50',
 '391_7': '2022-03-02 23:50',
 '391_8': '2022-03-02 23:50',
 '391_9': '2022-03-02 23:50',
 '392_3': '2022-03-02 23:55',
 '392_7': '2022-03-02 23:55',
 '392_8': '2022-03-02 23:55',
 '392_9': '2022-03-02 23:55',
 '393_3': '2022-03-03 00:00',
 '393_7': '2022-03-03 00:00',
 '393_8': '2022-03-03 00:00',
 '393_9': '2022-03-03 00:00',
 '394_3': '2022-03-03 00:05',
 '394_7': '2022-03-03 00:05',
 '394_8': '2022-03-03 00:05',
 '394_9': '2022-03-03 00:05',
 '395_3': '2022-03-03 00:10',
 '395_7': '2022-03-03 00:10',
 '395_8': '2022-03-03 00:10',
 '395_9': '2022-03-03 00:10',
 '396_3': '2022-03-03 00:15',
 '396_7': '2022-03-03 00:15',
 '396_8': '2022-03-03 00:15',
 '396_9': '2022-03-03 00:15',
 '397_3': '2022-03-03 00:20',
 '397_7': '2022-03-03 00:20',
 '397_8': '2022-03-03 00:20',
 '397_9': '2022-03-03 00:20',
 '398_3': '2022-03-03 00:25',
 '398_7': '2022-03-03 00:25',
 '398_8': '2022-03-03 00:25',
 '398_9': '2022-03-03 00:25',
 '399_3': '2022-03-03 00:30',
 '399_7': '2022-03-03 00:30',
 '399_8': '2022-03-03 00:30',
 '399_9': '2022-03-03 00:30',